// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNv52UunEjyRwqHHY7j1RwNkFu1ZOCRtY',
    appId: '1:514800539384:web:fb27baeea510d78615cd0d',
    messagingSenderId: '514800539384',
    projectId: 'fir-flutter-codelab-ce42b',
    authDomain: 'fir-flutter-codelab-ce42b.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ce42b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpTcmMsYOzT55E5SIMOCoaPdbRpruqFEU',
    appId: '1:514800539384:android:3a27cd93138a27e815cd0d',
    messagingSenderId: '514800539384',
    projectId: 'fir-flutter-codelab-ce42b',
    storageBucket: 'fir-flutter-codelab-ce42b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiNYIISAnccycJa046q7-Z0tYkXO81tAs',
    appId: '1:514800539384:ios:13a12ddacc1c808e15cd0d',
    messagingSenderId: '514800539384',
    projectId: 'fir-flutter-codelab-ce42b',
    storageBucket: 'fir-flutter-codelab-ce42b.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiNYIISAnccycJa046q7-Z0tYkXO81tAs',
    appId: '1:514800539384:ios:13a12ddacc1c808e15cd0d',
    messagingSenderId: '514800539384',
    projectId: 'fir-flutter-codelab-ce42b',
    storageBucket: 'fir-flutter-codelab-ce42b.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNv52UunEjyRwqHHY7j1RwNkFu1ZOCRtY',
    appId: '1:514800539384:web:f0253c6dbead880115cd0d',
    messagingSenderId: '514800539384',
    projectId: 'fir-flutter-codelab-ce42b',
    authDomain: 'fir-flutter-codelab-ce42b.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ce42b.firebasestorage.app',
  );
}
